### PR TITLE
Jakarta HealthCheckServlet object mapper and status indicator

### LINKED ISSUE #3918: Overriding HTTP status code of healthcheck servlet is not possible anymore
We upgraded from Dropwizard 2.1 to 4.0. Now [our monitoring](https://www.paessler.com/manuals/prtg/rest_custom_sensor) [fails](https://github.com/dropwizard/metrics/pull/1821#issuecomment-805841285) to get details in case of any unhealthy healthcheck because then the HTTP status 500 is used. Previously it was possible to [override](https://github.com/dropwizard/metrics/pull/1871) this, but that change was only done in [com.codahale.metrics.servlets.HealthCheckServlet](https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-servlets/src/main/java/com/codahale/metrics/servlets/HealthCheckServlet.java), not in [io.dropwizard.metrics.servlets.HealthCheckServlet](https://github.com/dropwizard/metrics/blob/release/4.2.x/metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/HealthCheckServlet.java) which our application now uses.

### PR DESCRIPTION
**Pull request by joschi**
- Allow overriding the `ObjectMapper` instance used in `HealthCheckServlet` with the servlet attribute `io.dropwizard.metrics.servlets.HealthCheckServlet.mapper`
- Allow setting the HTTP status code used to indicate health to 200 (OK) with the servlet attribute `io.dropwizard.metrics.servlets.HealthCheckServlet.httpStatusIndicator`, or with the HTTP query parameter `httpStatusIndicator` per request

Refs #1821
Refs #1871
Fixes #3918

### CODE REVIEW

File: metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java [hunk 1]
```diff
@@ -266,4 +217,39 @@ public void constructorWithRegistryAsArgumentUsesServletConfigWhenNullButWrongTy
...
         healthCheckServlet.init(servletConfig);
     }
+
+    @Test
+    public void constructorWithObjectMapperAsArgumentUsesServletConfigWhenNullButWrongTypeInContext() throws Exception {
+        final ServletContext servletContext = mock(ServletContext.class);
+        final ServletConfig servletConfig = mock(ServletConfig.class);
+        when(servletConfig.getServletContext()).thenReturn(servletContext);
+        when(servletContext.getAttribute(HealthCheckServlet.HEALTH_CHECK_REGISTRY)).thenReturn(registry);
+        when(servletContext.getAttribute(HealthCheckServlet.HEALTH_CHECK_MAPPER)).thenReturn("IRELLEVANT_STRING");
```
Comment (maffe) [inline metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java:227]: irrelevant typo

Comment (joschi) [reply metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java:227]: But at least it's a _consistent_ type. 😂 
```
❯ rg IRELLEVANT_STRING
metrics-servlets/src/test/java/com/codahale/metrics/servlets/MetricsServletTest.java
258:                .thenReturn("IRELLEVANT_STRING");

metrics-servlets/src/test/java/com/codahale/metrics/servlets/HealthCheckServletTest.java
217:                .thenReturn("IRELLEVANT_STRING");
229:        when(servletContext.getAttribute(HealthCheckServlet.HEALTH_CHECK_MAPPER)).thenReturn("IRELLEVANT_STRING");

metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/MetricsServletTest.java
258:                .thenReturn("IRELLEVANT_STRING");

metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java
215:                .thenReturn("IRELLEVANT_STRING");
227:        when(servletContext.getAttribute(HealthCheckServlet.HEALTH_CHECK_MAPPER)).thenReturn("IRELLEVANT_STRING");
```
